### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by florianluedtke** [gvellut/FreehandRasterGeoreferencer#3] opened 2016-08-03 07:29 UTC
When I try to open a jpg file, I get an error message which says: 

2016-08-03T09:26:17 1   Traceback (most recent call last):
              File "C:/Users/fluedtke/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer.py", line 190, in addLayer
                self.createFreehandRasterGeoreferencerLayer()
              File "C:/Users/fluedtke/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer.py", line 201, in createFreehandRasterGeoreferencerLayer
                layer = FreehandRasterGeoreferencerLayer(self, imagePath , imageName, screenExtent)
              File "C:/Users/fluedtke/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer_layer.py", line 46, in **init**
                self.initializeLayer(screenExtent)
              File "C:/Users/fluedtke/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer_layer.py", line 157, in initializeLayer
                self.resetScale(sw, sh)
              File "C:/Users/fluedtke/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer_layer.py", line 166, in resetScale
                wratio = sw / iw
            ZeroDivisionError: float division by zero

Some jpeg open, some do not... seems as if it's a random game ;)

**Comment by gvellut** [comment] 2016-08-09 20:06
Can you send a JPEG with the issue?

**Comment by Dkrav-UA** [comment] 2016-08-09 20:55
The same image can be with an error or without it. The problem is in QImage. Sometimes it returns zeros in image info.

**Comment by SzieberthAdam** [comment] 2016-11-03 11:30
+1

**Comment by radbun227** [comment] 2017-01-24 04:29
Same problem. Cannot load the JPEG is too big.

**Comment by gvellut** [comment] 2018-05-29 18:41
Closing. Can't reproduce.

**Closed by gvellut** 2018-05-29 18:41 UTC
Labels: bug

**Comment by mmokrejs** [comment] 2022-11-27 20:46
Same here with `0.8.3` version and `qgis-3.28.1`:

```
An error has occurred while executing Python code: 

ZeroDivisionError: float division by zero 
Traceback (most recent call last):
  File "/home/foo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer.py", line 290, in addLayer
    self.createFreehandRasterGeoreferencerLayer()
  File "/home/foo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer.py", line 311, in createFreehandRasterGeoreferencerLayer
    layer = FreehandRasterGeoreferencerLayer(
  File "/home/foo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer_layer.py", line 86, in __init__
    self.initializeLayer(screenExtent)
  File "/home/foo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer_layer.py", line 265, in initializeLayer
    self.resetScale(sw, sh)
  File "/home/foo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer_layer.py", line 387, in resetScale
    wratio = sw / iw
ZeroDivisionError: float division by zero


Python version: 3.9.15 (main, Nov 15 2022, 00:53:10) [GCC 12.2.1 20221008] 
QGIS version: 3.28.1-Firenze Firenze, exported 
```
